name: PHP Compatibility
on:
  push:

jobs:
  phpcompatibility:
    runs-on: ubuntu-latest
    name: PHP Compatibility
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: PHPCompatibility
        uses: pantheon-systems/phpcompatibility-action@v1
        with:
          test-versions: 7.4-
  lint:
    runs-on: ${{ matrix.operating-system }}
    name: Lint checks - PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ 'macos-latest' ]
        php-versions: [ '7.4', '8.0', '8.2', '8.4' ]
      max-parallel: 3
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: gd, mbstring, zip, ssh2-1.3.1, pcov
          coverage: pcov
          ini-values: error_reporting=E_ALL
      - name: Full Composer Install
        run: composer install
      - name: Lint check
        run: composer lint
      - name: Deprecations check
        run: composer deprecations
